services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: cycle_generator
    command: /app/bin/cycle_generator
    environment:
      ENV: production
      STATSD_ADDR: statsd:8125
    depends_on:
    - statsd
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
    - 8126:8126
    - 8000:80
    - 8080:8080
    volumes:
      - graphite-storage:/opt/graphite/storage
      - ../statsd/config/:/opt/statsd/config/:ro
  prometheus:
    image: prom/prometheus
    volumes:
    - prometheus-storage:/prometheus
    - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
    - statsd
volumes:
  graphite-storage:
  grafana-storage:
  prometheus-storage:
