services:
  statsd:
    image: graphiteapp/graphite-statsd
    ports:
    - 8126:8126
    - 8000:80
    - 8080:8080
    volumes:
      - statsd-storage:/opt/graphite/storage
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: cycle_generator
    command: /app/bin/cycle_generator
    environment:
      ENV: production
      STATSD_ADDR: statsd:8125
    depends_on:
    - statsd
  grafana:
    image: grafana/grafana
    ports:
    - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  statsd-storage:
  grafana-storage:
